language: python
python:
  - "3.6"
node_js: -"4.16.0"
addons:
  ssh_known_hosts: c4dtsrv1.epfl.ch
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.37.2/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 14 #LTS ends on 2023-04-30
  - node --version #solely for debugging purposes

stages:
  - test
  - prettier_pass
  - name: deploy
    if: branch = main

jobs:
  include:
    - stage: test
      script: pytest
      install: pip install -r requirements.txt

    - stage: prettier_pass
      install:
        - "npm install -g npm"
      script: npx prettier --check .

    - stage: deploy
      install: skip
      script: skip
      before_deploy:
        - echo "$DEPLOY_SSH_KEY" > "$HOME/.ssh/id_ed25519"
        - chmod 600 "$HOME/.ssh/id_ed25519"
      deploy:
        provider: script
        script: ssh factory@c4dtsrv1.epfl.ch mkdir -p bin && scp update.sh factory@c4dtsrv1.epfl.ch:bin/ && ssh factory@c4dtsrv1.epfl.ch bin/update.sh
        on:
          branch: main

notifications:
  email: false
